### PR TITLE
Switch docs to use sphinx material

### PR DESCRIPTION
**Pull request by Lunarmagpie**
I think it looks a lot better than furo

https://sphinx-book-theme.readthedocs.io/en/stable/

### CODE REVIEW

**Comment by HyperGH** [comment]
Does this support a dark theme?

**Comment by Lunarmagpie** [comment]
After looking into it I think it doesn't. I think I might switch this to pydata theme.
https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html

**Comment by HyperGH** [comment]
I think furo looks better than pydata, however if you prefer it, I'm fine with it too.

**Comment by Lunarmagpie** [comment]
Hosting it (here)[https://lunarmagpie.github.io/hikari-flare/]
Not sure if better tbh

**Comment by Lunarmagpie** [comment]
Closing because I don't think changing the doc themes is very important right now. I will reopen this later.

**Pull request closed without merging**
